-- MySQL Script generated by MySQL Workbench
-- 10/30/17 09:03:04
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema codeigniter
-- -----------------------------------------------------
-- This is database schema for codeigniter boilerplate. Created at Sep 4th 2017

-- -----------------------------------------------------
-- Schema codeigniter
--
-- This is database schema for codeigniter boilerplate. Created at Sep 4th 2017
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `codeigniter` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `codeigniter` ;

-- -----------------------------------------------------
-- Table `codeigniter`.`app_roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `codeigniter`.`app_roles` ;

CREATE TABLE IF NOT EXISTS `codeigniter`.`app_roles` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(80) NULL,
  `alias` VARCHAR(80) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `codeigniter`.`app_users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `codeigniter`.`app_users` ;

CREATE TABLE IF NOT EXISTS `codeigniter`.`app_users` (
  `id` BIGINT(22) NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(100) NULL,
  `password` VARCHAR(200) NULL,
  `salt` VARCHAR(200) NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `otp` VARCHAR(6) NULL,
  `app_role_id` INT(11) NOT NULL,
  `status` INT(1) NULL,
  `full_name` VARCHAR(100) NULL,
  `bio` TEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_app_users_app_role1_idx` (`app_role_id` ASC),
  CONSTRAINT `fk_app_users_app_role1`
    FOREIGN KEY (`app_role_id`)
    REFERENCES `codeigniter`.`app_roles` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `codeigniter`.`app_sessions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `codeigniter`.`app_sessions` ;

CREATE TABLE IF NOT EXISTS `codeigniter`.`app_sessions` (
  `token` VARCHAR(200) NOT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `user_agent` TEXT NULL,
  `ip_address` VARCHAR(128) NULL,
  `app_users_id` BIGINT(22) NOT NULL,
  PRIMARY KEY (`token`),
  INDEX `fk_app_session_app_users_idx` (`app_users_id` ASC),
  CONSTRAINT `fk_app_session_app_users`
    FOREIGN KEY (`app_users_id`)
    REFERENCES `codeigniter`.`app_users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `codeigniter`.`app_confirmations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `codeigniter`.`app_confirmations` ;

CREATE TABLE IF NOT EXISTS `codeigniter`.`app_confirmations` (
  `token` VARCHAR(64) NOT NULL,
  `app_users_id` BIGINT(22) NOT NULL,
  `type` ENUM('F','P') NULL COMMENT 'F: Forgot; P: Pending',
  PRIMARY KEY (`token`),
  INDEX `fk_app_pending_app_users1_idx` (`app_users_id` ASC),
  CONSTRAINT `fk_app_pending_app_users1`
    FOREIGN KEY (`app_users_id`)
    REFERENCES `codeigniter`.`app_users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `codeigniter`.`app_modules`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `codeigniter`.`app_modules` ;

CREATE TABLE IF NOT EXISTS `codeigniter`.`app_modules` (
  `id` VARCHAR(80) NOT NULL,
  `name` VARCHAR(80) NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `status` INT(1) NULL,
  `version` VARCHAR(8) NULL,
  `type` ENUM('S','A') NULL DEFAULT 'A' COMMENT 'S: System\'s Module\nA: Application\'s Module',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `codeigniter`.`app_access`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `codeigniter`.`app_access` ;

CREATE TABLE IF NOT EXISTS `codeigniter`.`app_access` (
  `id` BIGINT(22) NOT NULL AUTO_INCREMENT,
  `app_modules_id` VARCHAR(80) NOT NULL,
  `class_name` VARCHAR(80) NULL,
  `access_name` VARCHAR(80) NULL,
  INDEX `fk_app_classes_app_modules1_idx` (`app_modules_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_app_classes_app_modules1`
    FOREIGN KEY (`app_modules_id`)
    REFERENCES `codeigniter`.`app_modules` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `codeigniter`.`app_permissions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `codeigniter`.`app_permissions` ;

CREATE TABLE IF NOT EXISTS `codeigniter`.`app_permissions` (
  `id` BIGINT(22) NOT NULL AUTO_INCREMENT,
  `app_access_id` BIGINT(22) NOT NULL,
  `app_roles_id` INT(11) NOT NULL,
  `add` INT(1) NULL DEFAULT 0,
  `edit` INT(1) NULL DEFAULT 0,
  `detail` INT(1) NULL DEFAULT 0,
  `delete` INT(1) NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fk_app_permissions_app_access1_idx` (`app_access_id` ASC),
  INDEX `fk_app_permissions_app_roles1_idx` (`app_roles_id` ASC),
  CONSTRAINT `fk_app_permissions_app_access1`
    FOREIGN KEY (`app_access_id`)
    REFERENCES `codeigniter`.`app_access` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_app_permissions_app_roles1`
    FOREIGN KEY (`app_roles_id`)
    REFERENCES `codeigniter`.`app_roles` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `codeigniter`.`app_menus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `codeigniter`.`app_menus` ;

CREATE TABLE IF NOT EXISTS `codeigniter`.`app_menus` (
  `id` BIGINT(22) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(80) NOT NULL,
  `custom_url` VARCHAR(300) NULL,
  `type` INT(1) NULL DEFAULT 1 COMMENT '1: Internal Menu\n2: External Menu',
  `app_access_id` BIGINT(22) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_app_menu_app_access1_idx` (`app_access_id` ASC),
  CONSTRAINT `fk_app_menu_app_access1`
    FOREIGN KEY (`app_access_id`)
    REFERENCES `codeigniter`.`app_access` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `codeigniter`.`app_settings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `codeigniter`.`app_settings` ;

CREATE TABLE IF NOT EXISTS `codeigniter`.`app_settings` (
  `itemset` VARCHAR(120) NOT NULL,
  `val1` VARCHAR(800) NULL,
  `val2` VARCHAR(800) NULL,
  `val3` VARCHAR(800) NULL,
  `val4` VARCHAR(800) NULL,
  `val5` VARCHAR(800) NULL,
  `val6` VARCHAR(800) NULL,
  PRIMARY KEY (`itemset`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `codeigniter`.`app_notifications`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `codeigniter`.`app_notifications` ;

CREATE TABLE IF NOT EXISTS `codeigniter`.`app_notifications` (
  `id` VARCHAR(100) NOT NULL,
  `title` VARCHAR(120) NOT NULL,
  `content` VARCHAR(600) NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `is_read` INT(1) NULL DEFAULT 0,
  `app_users_id` BIGINT(22) NOT NULL,
  `url` VARCHAR(800) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_app_notifications_app_users1_idx` (`app_users_id` ASC),
  CONSTRAINT `fk_app_notifications_app_users1`
    FOREIGN KEY (`app_users_id`)
    REFERENCES `codeigniter`.`app_users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `codeigniter`.`app_menu_roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `codeigniter`.`app_menu_roles` ;

CREATE TABLE IF NOT EXISTS `codeigniter`.`app_menu_roles` (
  `id` BIGINT(22) NOT NULL AUTO_INCREMENT,
  `order` INT(5) NULL,
  `app_roles_id` INT(11) NOT NULL,
  `app_menus_id` BIGINT(22) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_app_menu_roles_app_roles1_idx` (`app_roles_id` ASC),
  INDEX `fk_app_menu_roles_app_menus1_idx` (`app_menus_id` ASC),
  CONSTRAINT `fk_app_menu_roles_app_roles1`
    FOREIGN KEY (`app_roles_id`)
    REFERENCES `codeigniter`.`app_roles` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_app_menu_roles_app_menus1`
    FOREIGN KEY (`app_menus_id`)
    REFERENCES `codeigniter`.`app_menus` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `codeigniter`.`app_divisions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `codeigniter`.`app_divisions` ;

CREATE TABLE IF NOT EXISTS `codeigniter`.`app_divisions` (
  `id` BIGINT(22) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(180) NULL,
  `is_access_all` INT(1) NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `codeigniter`.`app_user_divisions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `codeigniter`.`app_user_divisions` ;

CREATE TABLE IF NOT EXISTS `codeigniter`.`app_user_divisions` (
  `id` BIGINT(22) NOT NULL AUTO_INCREMENT,
  `app_users_id` BIGINT(22) NOT NULL,
  `app_divisions_id` BIGINT(22) NOT NULL,
  PRIMARY KEY (`id`, `app_users_id`),
  INDEX `fk_app_user_divisions_app_users1_idx` (`app_users_id` ASC),
  INDEX `fk_app_user_divisions_app_divisions1_idx` (`app_divisions_id` ASC),
  CONSTRAINT `fk_app_user_divisions_app_users1`
    FOREIGN KEY (`app_users_id`)
    REFERENCES `codeigniter`.`app_users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_app_user_divisions_app_divisions1`
    FOREIGN KEY (`app_divisions_id`)
    REFERENCES `codeigniter`.`app_divisions` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `codeigniter`.`app_division_access`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `codeigniter`.`app_division_access` ;

CREATE TABLE IF NOT EXISTS `codeigniter`.`app_division_access` (
  `id` BIGINT(22) NOT NULL AUTO_INCREMENT,
  `app_divisions_id` BIGINT(22) NOT NULL,
  `division_access` BIGINT(22) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_app_division_access_app_divisions1_idx` (`app_divisions_id` ASC),
  INDEX `fk_app_division_access_app_divisions2_idx` (`division_access` ASC),
  CONSTRAINT `fk_app_division_access_app_divisions1`
    FOREIGN KEY (`app_divisions_id`)
    REFERENCES `codeigniter`.`app_divisions` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_app_division_access_app_divisions2`
    FOREIGN KEY (`division_access`)
    REFERENCES `codeigniter`.`app_divisions` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `codeigniter`.`app_roles`
-- -----------------------------------------------------
START TRANSACTION;
USE `codeigniter`;
INSERT INTO `codeigniter`.`app_roles` (`id`, `name`, `alias`) VALUES (1, 'Administrator', NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `codeigniter`.`app_users`
-- -----------------------------------------------------
START TRANSACTION;
USE `codeigniter`;
INSERT INTO `codeigniter`.`app_users` (`id`, `email`, `password`, `salt`, `created_at`, `otp`, `app_role_id`, `status`, `full_name`, `bio`) VALUES (1, 'admin@example.com', 'ed5a6ec4e722a7c8fe5fef89b5d6332ae25ba9e421ba5c45d362587339d0ef9442d96d5d334d4a576f095168e5e8936318e48c6066879b75702340469d7eae99', 'DPaOcaDpKgLXZtiT2s5Han5mpcodBGekqbrQ4oYhOZvS1vXrN6vlwYzkSl9kwCTRQshQnI0DoEBKTfjJgi3bN3FZ0Vi8RVH4UqtUmF4LA6exM20U5NfzG9tAG1C8myRc', NOW(), NULL, 1, 1, 'John Doe', 'This is user\'s bio or description.');

COMMIT;


-- -----------------------------------------------------
-- Data for table `codeigniter`.`app_settings`
-- -----------------------------------------------------
START TRANSACTION;
USE `codeigniter`;
INSERT INTO `codeigniter`.`app_settings` (`itemset`, `val1`, `val2`, `val3`, `val4`, `val5`, `val6`) VALUES ('NewUserRole', '1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `codeigniter`.`app_settings` (`itemset`, `val1`, `val2`, `val3`, `val4`, `val5`, `val6`) VALUES ('NewUserDivision', '1', NULL, NULL, NULL, NULL, NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `codeigniter`.`app_divisions`
-- -----------------------------------------------------
START TRANSACTION;
USE `codeigniter`;
INSERT INTO `codeigniter`.`app_divisions` (`id`, `name`, `is_access_all`) VALUES (1, 'General', NULL);

COMMIT;

