-- MySQL Script generated by MySQL Workbench
-- 10/03/17 15:23:56
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema codeigniter
-- -----------------------------------------------------
-- This is database schema for codeigniter boilerplate. Created at Sep 4th 2017

-- -----------------------------------------------------
-- Schema codeigniter
--
-- This is database schema for codeigniter boilerplate. Created at Sep 4th 2017
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `codeigniter` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `codeigniter` ;

-- -----------------------------------------------------
-- Table `codeigniter`.`app_roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `codeigniter`.`app_roles` ;

CREATE TABLE IF NOT EXISTS `codeigniter`.`app_roles` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(80) NULL,
  `alias` VARCHAR(80) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `codeigniter`.`app_users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `codeigniter`.`app_users` ;

CREATE TABLE IF NOT EXISTS `codeigniter`.`app_users` (
  `id` BIGINT(22) NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(100) NULL,
  `password` VARCHAR(200) NULL,
  `salt` VARCHAR(200) NULL,
  `created_at` DATETIME NULL,
  `otp` VARCHAR(6) NULL,
  `app_role_id` INT(11) NOT NULL,
  `status` INT(1) NULL,
  `full_name` VARCHAR(100) NULL,
  `bio` TEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_app_users_app_role1_idx` (`app_role_id` ASC),
  CONSTRAINT `fk_app_users_app_role1`
    FOREIGN KEY (`app_role_id`)
    REFERENCES `codeigniter`.`app_roles` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `codeigniter`.`app_sessions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `codeigniter`.`app_sessions` ;

CREATE TABLE IF NOT EXISTS `codeigniter`.`app_sessions` (
  `token` VARCHAR(200) NOT NULL,
  `created_at` DATETIME NULL,
  `user_agent` TEXT NULL,
  `ip_address` VARCHAR(128) NULL,
  `app_users_id` BIGINT(22) NOT NULL,
  PRIMARY KEY (`token`),
  INDEX `fk_app_session_app_users_idx` (`app_users_id` ASC),
  CONSTRAINT `fk_app_session_app_users`
    FOREIGN KEY (`app_users_id`)
    REFERENCES `codeigniter`.`app_users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `codeigniter`.`app_confirmations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `codeigniter`.`app_confirmations` ;

CREATE TABLE IF NOT EXISTS `codeigniter`.`app_confirmations` (
  `token` VARCHAR(64) NOT NULL,
  `app_users_id` BIGINT(22) NOT NULL,
  `type` ENUM('F','P') NULL COMMENT 'F: Forgot; P: Pending',
  PRIMARY KEY (`token`),
  INDEX `fk_app_pending_app_users1_idx` (`app_users_id` ASC),
  CONSTRAINT `fk_app_pending_app_users1`
    FOREIGN KEY (`app_users_id`)
    REFERENCES `codeigniter`.`app_users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `codeigniter`.`app_modules`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `codeigniter`.`app_modules` ;

CREATE TABLE IF NOT EXISTS `codeigniter`.`app_modules` (
  `id` VARCHAR(80) NOT NULL,
  `name` VARCHAR(80) NULL,
  `created_at` DATETIME NULL,
  `status` INT(1) NULL,
  `version` VARCHAR(8) NULL,
  `type` ENUM('S','A') NULL DEFAULT 'A' COMMENT 'S: System\'s Module\nA: Application\'s Module',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `codeigniter`.`app_access`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `codeigniter`.`app_access` ;

CREATE TABLE IF NOT EXISTS `codeigniter`.`app_access` (
  `id` BIGINT(22) NOT NULL AUTO_INCREMENT,
  `app_modules_id` VARCHAR(80) NOT NULL,
  `class_name` VARCHAR(80) NULL,
  `access_name` VARCHAR(80) NULL,
  INDEX `fk_app_classes_app_modules1_idx` (`app_modules_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_app_classes_app_modules1`
    FOREIGN KEY (`app_modules_id`)
    REFERENCES `codeigniter`.`app_modules` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `codeigniter`.`app_permissions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `codeigniter`.`app_permissions` ;

CREATE TABLE IF NOT EXISTS `codeigniter`.`app_permissions` (
  `id` BIGINT(22) NOT NULL AUTO_INCREMENT,
  `app_access_id` BIGINT(22) NOT NULL,
  `app_roles_id` INT(11) NOT NULL,
  `add` INT(1) NULL DEFAULT 0,
  `edit` INT(1) NULL DEFAULT 0,
  `detail` INT(1) NULL DEFAULT 0,
  `delete` INT(1) NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fk_app_permissions_app_access1_idx` (`app_access_id` ASC),
  INDEX `fk_app_permissions_app_roles1_idx` (`app_roles_id` ASC),
  CONSTRAINT `fk_app_permissions_app_access1`
    FOREIGN KEY (`app_access_id`)
    REFERENCES `codeigniter`.`app_access` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_app_permissions_app_roles1`
    FOREIGN KEY (`app_roles_id`)
    REFERENCES `codeigniter`.`app_roles` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `codeigniter`.`app_roles`
-- -----------------------------------------------------
START TRANSACTION;
USE `codeigniter`;
INSERT INTO `codeigniter`.`app_roles` (`id`, `name`, `alias`) VALUES (1, 'Administrator', NULL);
INSERT INTO `codeigniter`.`app_roles` (`id`, `name`, `alias`) VALUES (2, 'User', NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `codeigniter`.`app_users`
-- -----------------------------------------------------
START TRANSACTION;
USE `codeigniter`;
INSERT INTO `codeigniter`.`app_users` (`id`, `email`, `password`, `salt`, `created_at`, `otp`, `app_role_id`, `status`, `full_name`, `bio`) VALUES (NULL, 'admin@example.com', NULL, NULL, 'NOW()', NULL, 1, 1, 'John Doe', 'This is user\'s bio or description.');

COMMIT;

